on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hi_world
        uses: kyledeanreinford/test-javascript-action@v2
        with:
          who-to-greet: 'kdr'
      - name: Get the output time
        run: echo "The time was ${{ steps.hi_world.outputs.time }}"